pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                echo 'Cloning...'
                sh '''
                git clone https://github.com/edgaregonzalez/app-devops-bootcamp
                '''
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
    }
}